name: Emscripten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  js-build:
    name: Build liblouis for js

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Install dependencies
    #   run: sudo apt-get update -qq && sudo apt-get install -y clang-format-7
    - name: Obtain liblouis-js
      # Contains tests and js snippets appended to builds. liblouis-js
      # version should be incremented by hand, to keep the
      # repositories in sync.
      run: git clone https://github.com/liblouis/liblouis-js.git
    - name: Pull the docker image
      run: docker pull dolp/liblouis-js-build-travis:1.37.3-64bit

    - name: Run the docker image
      run: docker run --rm -v $(pwd):/src dolp/liblouis-js-build-travis:1.37.3-64bit /bin/bash  ".travis/script/emscripten-build.sh"

    - name: debug
      run: find ./liblouis-js

    - name: Move the build result to a better place
      run: cp -rf ./out/* ./liblouis-js/js-build

    - name: Build and test the npm package
      run: |
        cd ./liblous-js
        npm link js-build --production
        npm run test-node
        cd ..

